### ISSUE TITLE
Allow autocomplete within placeholders

### ISSUE THREAD

**Issue by tomak-git** [rundis/lt-snippets#15]
When using placeholders Light Table's autocomplete function is suspended.

Steps to reproduce:
1. Create a snippet with a placeholder in it.
2. Type the triggering letters, hit Snippets: Expand by editor token.
3. When typing within the placeholder, autocomplete does not work.

It would be great to have access to autocomplete when typing within placeholders.

**Comment by rundis** [comment]
Closing due to low cost benefit ratio and not enough spare time. Feel free to submit a pull request though.
