### ISSUE TITLE
Edit snippets

### ISSUE THREAD

**Issue by skrat** [rundis/lt-snippets#16]
Not bad at all this plugin! Thank you! Feature request: it'd be nice to have a way to edit snippets from LT without resorting to shell/vim (so far fastest way I found). Eg. Ctrl+Space...Snippet manager... would show list of snippets, add/edit/remove (navigable from keboard) Hard? Easy? Good feature? I'd say so, what do you think?

**Comment by rundis** [comment]
I don't have the bandwith for doing this feature, and to me the benefit cost ratio seems a little low. Pull request welcome though.
